#!/bin/bash
# Create-Windows-USB
# By chris1111
# Copyright (c) 2023, chris1111. All Right Reserved
# Credit: Wimlib Eric Biggers
# Vars
apptitle="Create-Windows"
version="1.0"
# Set Icon directory and file 
iconfile="/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/com.apple.imac-aluminum-20.icns"

# Unmount Volumes/WIN if mount
osascript <<EOD
tell application "Finder"
	activate
	if exists disk "WIN" then
		tell application "Finder" to eject disk "WIN"
		
	end if
end tell
EOD
# Unmount Volumes/WimlibDev if mount
osascript <<EOD
tell application "Finder"
	activate
	if exists disk "WimlibDev" then
		tell application "Finder" to eject disk "WimlibDev"
		
	end if
end tell
EOD
echo "Create-Windows-USB"
echo "
--------------------------------------------------------------"
echo "Starting --> "`date "+%Y-%m-%d %H:%M:%S"`""
echo "
--------------------------------------------------------------"

response=$(osascript -e 'tell app "System Events" to display dialog "
Welcome Create Windows USB
Please make a choice\nCancel for Exit" buttons {"Cancel", "Create Windows USB"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')


answer=$(echo $response | grep "Create Windows USB")


# Cancel is user does not select Create Windows USB
if [ ! "$answer" ] ; then
  Umount -f /Volumes/WIN
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  echo "Create-Windows-USB Exit User cancelled"
  Sleep 3
  echo "QUITAPP"
fi


osascript <<EOD
  tell application "Create-Windows-USB"
      activate
  end tell
EOD

echo "
Mount Wimlib 1.14.1
--------------------------------------------------------------"
hdiutil attach -noverify -nobrowse ./WimlibDev.dmg

osascript <<EOD

# Script Created USB Disk Window in macOS by chris1111
display alert "Format your USB Drive with Disk Utility in the format MS-DOS (FAT32)
Master Boot Record
*****************************
You must quit Disk Utility to continue installation." buttons {"Create USB Windows"} as critical default button 1 giving up after 60
# Open Disk Utility
do shell script "open -F -a 'Disk Utility'"
delay 1
tell application "Disk Utility"
	activate
end tell

repeat
	if application "Disk Utility" is not running then exit repeat
	
end repeat

delay 2

# Choose Rename USB Disk
activate me
set all to paragraphs of (do shell script "ls /Volumes")
set w to choose from list all with prompt " 
Select the volume that you just formatted, then press the OK button
The volume will be renamed WINUSB" OK button name "OK" with multiple selections allowed
if w is false then
	display dialog "Quit Installer " with icon 0 buttons {"EXIT"} default button {"EXIT"}
	return
end if
try
	
	repeat with teil in w
		do shell script "diskutil `diskutil list | awk '/ " & teil & "  / {print $NF}'`"
	end repeat
end try
set theName to "WINUSB"
tell application "Finder"
	set name of disk w to theName
end tell
set DiskImage to choose file with prompt "Please select your Windows ISO:" default location (path to desktop)
do shell script "hdiutil mount -noverify -nobrowse -mountpoint /Volumes/WIN " & quoted form of POSIX path of DiskImage



display alert "
**************************
Attach Windows image OK!
**************************" buttons {"Done"} default button 1 giving up after 1

EOD



osascript <<EOD
  tell application "Create-Windows-USB"
      activate
  end tell
EOD


echo "
--------------------------------------------------------------"
echo "RSYNC --> Copy Windows, this wil take a while. . . Wait!"
osascript -e 'do shell script "rsync -avh --progress --exclude=sources/install.wim /Volumes/WIN/ /Volumes/WINUSB" '
Sleep 2
echo "Done ✅"
echo "
--------------------------------------------------------------"
echo "Wimlib --> Split install.wim , this wil take a while. . . Wait!"
osascript -e 'do shell script "/Volumes/WimlibDev/usr/local/bin/wimlib-imagex split /Volumes/WIN/sources/install.wim /Volumes/WINUSB/sources/install.swm 3500" '

echo "WINUSB Create! All Done ✅"
echo "
--------------------------------------------------------------"
echo "
--------------------------------------------------------------"
echo "Finishing --> "`date "+%Y-%m-%d %H:%M:%S"`""
echo "
--------------------------------------------------------------"
Sleep 1
Umount -f /Volumes/WIN
Umount -f /Volumes/WimlibDev

